### ISSUE TITLE
Fix Linux CI build

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#3049]
The Linux CI build fails because of:
```
The following packages have unmet dependencies:
 libzip-dev : Depends: libzip4 (= 1.1.2-1.1) but 1.7.3-1+ubuntu18.04.1+deb.sury.org+2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I tried to reproduce it in a clean Ubuntu 18.04 Docker image and the problem doesn't appear there.

I tried to create a minimal workflow in a dummy repository:
```yml
name: Test

on:
  push

jobs:
  main-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libzip-dev
```
This fails with the same error message.

Therefore, the problem is specific to `libzip-dev` and the GitHub Action Ubuntu image.
